### ISSUE TITLE
udagram-api does not start with Node 14

### ISSUE THREAD

**Issue by fre5** [udacity/nd0067-c4-deployment-process-project-starter#35]
Replicate:
`npm install`
`npm run build`
`npm run start`

However, it works with Node 12

**Comment by MarcoTerzoloGit** [comment]
actually it was PG dependency too old. just update that and it works (lacks of support from udacity is unbelievable by the way)

**Comment by SudKul** [comment]
Thanks , @MarcoTerzoloGit, for reporting the issue. 
Thanks,  @MarcoTerzoloGit, for identifying the issue. 
While we are working in a limited capacity, it is not possible for us to take *proactive* steps to keep the repo updated. 
However, I will be happy to review your PR, if you can submit the enhancements to the starter code in this repo. 

Wishes
Udacity Content Team

**Comment by MarcoTerzoloGit** [comment]
> 

Thank you SudKul. Applied the edits I performed to avoid the downgrade to node 12 workaround, opened in pull request. regards, Marco
