### ISSUE TITLE
cannot find module 'v6/Model'

### ISSUE THREAD

**Issue by MarkWasfy00** [udacity/nd0067-c4-deployment-process-project-starter#52]
every time I install node_modules i get alot of valuabraility issues , so i had to clean cache & delete package.lock.json , node_modules , restart "npm install" and then i get this error 
![Screenshot 2022-09-23 082304](https://user-images.githubusercontent.com/76422492/191903249-62dfa3b6-7351-4ddd-af47-c039bb67d05a.png)

tried using node 14.15.1 and changing operating system but still getting the same error

**Comment by abdalla-yahia** [comment]
Me too !! I can't find a solution for this 
![Uploading لقطة الشاشة 2022-09-22 151409.png…]()

**Comment by abdalla-yahia** [comment]
![لقطة الشاشة 2022-09-22 151953](https://user-images.githubusercontent.com/94574716/192018789-1ad43e03-5262-47b5-acbb-a4721e9c3510.png)

**Comment by ahmedIbrahimKenawi** [comment]
"sequelize-typescript": "^0.6.9"  do NOT support sequelize version 6
updating sequelize-typescript should solve the error

npm i sequelize-typescript@2.1.3

**Comment by ahmedsomaa** [comment]
Upgrading "sequelize-typescript" to 2.1.3 causes the `npx tsc` to fail with errors.

![image](https://user-images.githubusercontent.com/29373629/199075522-3f4ec3d8-cce7-4446-b342-0ce6f402e944.png)

**Comment by ahmedsomaa** [comment]
managed to fix the `tsc` command by updating the following packages:
- "sequelize": "^6.25.3"
- "sequelize-typescript": "^2.1.5"
- "@types/node": "^18.11.8"
- "@types/validator": "^13.7.10"

now both `dev` and `build` scripts are working just fine.
